---
- name: This sets up an httpd webserver - Ansible Tower
  hosts: all
  tasks:
  - name: Install web components
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - apache2
      - mysql-server
    
  - name: Ensure apache2 started
    service: name=apache2 state=started enabled=yes


